[theme]
base = "dark"
primaryColor = "#7c6fea"
backgroundColor = "#080b12"
secondaryBackgroundColor = "#0e1219"
textColor = "#f1f4f9"
font = "sans serif"

[server]
headless = true
port = 8080
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
# Use the EXACT AWS URL here
serverAddress = 'j3pzzpju7m.us-east-1.awsapprunner.com'
serverPort = 443
